2023-06-23 00:54:40,307 TADA INFO starting test `direct_ldms_ls_conn_test`
2023-06-23 00:54:40,307 TADA INFO   test-id: 67bee5bf8dd8ad42a3a3ed4a66dfcae444e75c34cd3b41248382d0d58ce601ba
2023-06-23 00:54:40,307 TADA INFO   test-suite: LDMSD
2023-06-23 00:54:40,307 TADA INFO   test-name: direct_ldms_ls_conn_test
2023-06-23 00:54:40,307 TADA INFO   test-user: narate
2023-06-23 00:54:40,307 TADA INFO   commit-id: 564784aadef90522c9e94e7797b394d462daa25d
2023-06-23 00:54:40,543 __main__ INFO starting munged on cygnus-01-iw
2023-06-23 00:54:40,919 __main__ INFO starting munged on localhost
2023-06-23 00:54:41,145 __main__ INFO starting ldmsd on cygnus-01-iw
2023-06-23 00:54:41,598 TADA INFO assertion 0, Start ldmsd sampler and munged: OK, passed
2023-06-23 00:54:46,792 TADA INFO assertion 1, ldms_ls to the sampler: OK, passed
2023-06-23 00:54:46,792 __main__ INFO Stopping sampler daemon ...
Traceback (most recent call last):
  File "direct_ldms_ls_conn_test", line 296, in <module>
    samp.stop()
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 2242, in stop
    return self._remote_stop()
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 2238, in _remote_stop
    raise RuntimeError("remote stop error: {}, msg: {}".format(rc, out))
RuntimeError: remote stop error: 255, msg: pid file not found /mnt/300G/data/2023-06-23-003001/data/direct_ldms_ls_conn_test/pid/cygnus-01-iw/cygnus-01-iw-10001.pid

2023-06-23 00:54:46,996 TADA INFO assertion 2, Kill the sampler: skipped
2023-06-23 00:54:46,997 TADA INFO assertion 3, ldms_ls to the dead sampler: skipped
2023-06-23 00:54:46,997 TADA INFO assertion 4, ldms_ls to a dead host: skipped
2023-06-23 00:54:46,997 TADA INFO test direct_ldms_ls_conn_test ended
2023-06-23 00:54:47,199 __main__ INFO stopping munged on cygnus-01-iw
2023-06-23 00:54:47,618 __main__ INFO stopping munged on localhost
