2023-05-21 01:08:13,359 TADA INFO starting test `ldmsd_auth_test`
2023-05-21 01:08:13,360 TADA INFO   test-id: 15952b01ce44290c3ad18768161791b6ea1ba06bb269687f6036fbe08182684f
2023-05-21 01:08:13,360 TADA INFO   test-suite: LDMSD
2023-05-21 01:08:13,360 TADA INFO   test-name: ldmsd_auth_test
2023-05-21 01:08:13,360 TADA INFO   test-user: narate
2023-05-21 01:08:13,360 TADA INFO   commit-id: d403a90da67ae0dc1d9ef66d720f6227e28c1ace
2023-05-21 01:08:13,360 __main__ INFO -- Get or create the cluster --
2023-05-21 01:08:31,279 __main__ INFO -- Start daemons --
2023-05-21 01:08:49,884 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-05-21 01:08:54,998 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-05-21 01:08:55,109 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-05-21 01:08:55,233 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-05-21 01:08:55,350 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-05-21 01:08:55,487 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Sun May 21 01:08:55 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-05-21 01:08:55,487 TADA INFO test ldmsd_auth_test ended
