2023-05-15 01:07:07,873 TADA INFO starting test `ldmsd_auth_test`
2023-05-15 01:07:07,874 TADA INFO   test-id: 57302ea437d54dd2eafe4c74151cf2d6e06814167f55542cbf51a19fdf7c85ab
2023-05-15 01:07:07,874 TADA INFO   test-suite: LDMSD
2023-05-15 01:07:07,874 TADA INFO   test-name: ldmsd_auth_test
2023-05-15 01:07:07,874 TADA INFO   test-user: narate
2023-05-15 01:07:07,874 TADA INFO   commit-id: bf615e117c95b472fcd0941ff4734b25cb7cbaf9
2023-05-15 01:07:07,875 __main__ INFO -- Get or create the cluster --
2023-05-15 01:07:25,811 __main__ INFO -- Start daemons --
2023-05-15 01:07:44,677 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-05-15 01:07:49,821 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-05-15 01:07:49,928 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-05-15 01:07:50,060 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-05-15 01:07:50,175 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-05-15 01:07:50,291 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Mon May 15 01:07:50 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-05-15 01:07:50,291 TADA INFO test ldmsd_auth_test ended
