2023-04-10 01:02:32,246 TADA INFO starting test `ldmsd_auth_test`
2023-04-10 01:02:32,246 TADA INFO   test-id: f1bf9b58097ca8ca694a647182fa0aa43d0411a8943ae28d39f294109cab91aa
2023-04-10 01:02:32,247 TADA INFO   test-suite: LDMSD
2023-04-10 01:02:32,247 TADA INFO   test-name: ldmsd_auth_test
2023-04-10 01:02:32,247 TADA INFO   test-user: narate
2023-04-10 01:02:32,247 TADA INFO   commit-id: 21baf08f6cc91323a5fd20bf2a1498a48cd12731
2023-04-10 01:02:32,247 __main__ INFO -- Get or create the cluster --
2023-04-10 01:02:50,587 __main__ INFO -- Start daemons --
2023-04-10 01:03:09,569 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-04-10 01:03:14,694 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-04-10 01:03:14,817 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-04-10 01:03:14,945 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-04-10 01:03:15,048 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-04-10 01:03:15,156 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Mon Apr 10 01:03:15 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-04-10 01:03:15,156 TADA INFO test ldmsd_auth_test ended
