2023-04-15 01:03:36,278 TADA INFO starting test `ldmsd_auth_test`
2023-04-15 01:03:36,278 TADA INFO   test-id: 0234ccc613eb39f9607ab9881578141d12974b14f2ade9ed2cacd56299347ea8
2023-04-15 01:03:36,278 TADA INFO   test-suite: LDMSD
2023-04-15 01:03:36,278 TADA INFO   test-name: ldmsd_auth_test
2023-04-15 01:03:36,278 TADA INFO   test-user: narate
2023-04-15 01:03:36,278 TADA INFO   commit-id: 68e667bc44eaab858e3e6780ff486ecea127db3a
2023-04-15 01:03:36,279 __main__ INFO -- Get or create the cluster --
2023-04-15 01:03:54,102 __main__ INFO -- Start daemons --
2023-04-15 01:04:12,961 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-04-15 01:04:18,095 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-04-15 01:04:18,206 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-04-15 01:04:18,343 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-04-15 01:04:18,464 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-04-15 01:04:18,578 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Sat Apr 15 01:04:18 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-04-15 01:04:18,578 TADA INFO test ldmsd_auth_test ended
