2023-07-02 01:11:29,098 TADA INFO starting test `ldmsd_auth_test`
2023-07-02 01:11:29,098 TADA INFO   test-id: 063a865993f355cab09d5ddca0e9ca6581fd8ef16c0d6ade64b7065106535948
2023-07-02 01:11:29,098 TADA INFO   test-suite: LDMSD
2023-07-02 01:11:29,098 TADA INFO   test-name: ldmsd_auth_test
2023-07-02 01:11:29,098 TADA INFO   test-user: narate
2023-07-02 01:11:29,098 TADA INFO   commit-id: 26f8c63d31947afe7b20b74b1c158c9fdd735a13
2023-07-02 01:11:29,099 __main__ INFO -- Get or create the cluster --
2023-07-02 01:11:47,389 __main__ INFO -- Start daemons --
2023-07-02 01:12:33,818 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-07-02 01:12:38,955 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-07-02 01:12:39,069 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-07-02 01:12:39,187 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-07-02 01:12:39,306 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-07-02 01:12:39,413 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Sun Jul 02 01:12:39 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-07-02 01:12:39,413 TADA INFO test ldmsd_auth_test ended
