2025-09-12 01:18:06,649 TADA INFO starting test `maestro_cfg_test`
2025-09-12 01:18:06,649 TADA INFO   test-id: 80cb86ba624c7509c2e9e8d1b54988c1cebacd272c40af117c3dc8dcddb49e7d
2025-09-12 01:18:06,649 TADA INFO   test-suite: LDMSD
2025-09-12 01:18:06,649 TADA INFO   test-name: maestro_cfg_test
2025-09-12 01:18:06,649 TADA INFO   test-user: narate
2025-09-12 01:18:06,649 TADA INFO   commit-id: 7fec9d72999da1bd3560ba0668870f85552882da
2025-09-12 01:18:16,661 __main__ INFO -- Get or create cluster --
2025-09-12 01:19:01,789 __main__ INFO -- Start daemons --
2025-09-12 01:20:41,227 __main__ INFO ... make sure ldmsd's are up
2025-09-12 01:20:46,772 TADA INFO assertion 1, load maestro etcd cluster: Unexpected output: , failed
---Wait for config to write to file---
Traceback (most recent call last):
  File "maestro_cfg_test", line 324, in <module>
    test.assert_test(1, False, "Unexpected output: {}".format(out))
  File "/home/narate/cron/ldms-test/TADA.py", line 157, in assert_test
    raise AssertionException(self.test_desc + ", " + cond_str + ": FAILED")
TADA.AssertionException: Test for ldmsd configuration with maestro_ctrl, Unexpected output: : FAILED
2025-09-12 01:20:46,773 TADA INFO assertion 2, config ldmsd cluster with maestro: skipped
2025-09-12 01:20:46,773 TADA INFO assertion 3, verify sampler daemons: skipped
2025-09-12 01:20:46,773 TADA INFO assertion 4, verify L1 aggregator daemons: skipped
2025-09-12 01:20:46,773 TADA INFO assertion 5, verify L2 aggregator daemon: skipped
2025-09-12 01:20:46,774 TADA INFO assertion 6, verify data storage: skipped
2025-09-12 01:20:46,774 TADA INFO test maestro_cfg_test ended
